services:
  bot:
    image: ghcr.io/fyysikkokilta/fk-viikkotiedotebot:latest
    restart: always
    volumes:
      - ./logs:/bot/logs:rw
      - ./data:/bot/data:rw
      - ./mails:/bot/mails:rw
    env_file:
      - ./env/bot.env
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
