services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data:/bot/data:rw
      - ./mails:/bot/mails:rw
    env_file:
      - ./env/bot.env
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
